[client]
# Whether to enable livereload or not
showErrorDetails = true

[server]
# The address where the server will listen for client and browser connections
address = "localhost"
# The port where the server will listen for browser connections
port = 8501
# Enables support for Cross-Origin Resource Sharing (CORS) protection
enableCORS = true
# Max size for file uploads (increased for document processing)
maxUploadSize = 400
# Whether to enable websocket compression
enableWebsocketCompression = false

[browser]
# Whether to gather usage stats
gatherUsageStats = false

[theme]
# Primary colors
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[mapbox]
# Mapbox token (not needed for this project)
token = "" 