# API Keys - Replace with your actual keys
OPENAI_API_KEY = "your_openai_api_key_here"
GOOGLE_TRANSLATE_API_KEY = starry-academy-465514-j2-37ff80cd986b.json
GOOGLE_PROJECT_ID =starry-academy-465514-j2

# Optional: Neo4j Database Configuration
NEO4J_URI = "bolt://localhost:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "your_neo4j_password"

# Optional: Additional API Keys
HUGGINGFACE_API_KEY = "your_huggingface_api_key_here" 